// Generated by Selenium IDE
package com.leonardo.restaurantFinder.stepDefinition;
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
public class SearchSushiTest {
	
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  
  
  
  @Before
  public void setUp() {
	System.setProperty("webdriver.chrome.driver","C:\\xampp\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchSushi() {
    driver.get("https://leorestaurantfinder.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(987, 698));
    driver.findElement(By.id("nameSearch")).click();
    driver.findElement(By.id("nameSearch")).sendKeys("sushi");
    driver.findElement(By.id("nameSearch")).sendKeys(Keys.ENTER);
    driver.close();
  }
}
